xpeng: Add missing camera dependency blob
error: vendor/motorola/xpeng/Android.bp:2041:1: "com.qti.node.remosaic" depends on undefined module "libfcell".
Change-Id: Ia933431d18fac7a3bfb085ae4a98444dcc0ba10a